version: "3"
services:
  db:
    container_name: db
    restart: always
    image: timescale/timescaledb
    env_file: .env
    ports:
      - '9000:5432'
    volumes:
      - database:/var/lib/postgresql/data
  web:
    restart: always
    container_name: web
    expose:
    - "8000"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  database:
